### ISSUE TITLE
auth issue

### ISSUE THREAD

**Issue by slingr-dev** [gabe565/nightscout-menu-bar#31]
Hello,
I have `AUTH_DEFAULT_ROLES=denied` set and created a readable access token

I am able to access my nightscout instance via `https://cgm.mynightscoutdomain.com/?token=menubar-6900739a9dff6e86`

I am getting the following error when utilizing the above URL with the menu bar

<img width="390" alt="Screenshot 2023-10-26 at 02 06 59" src="https://github.com/gabe565/nightscout-menu-bar/assets/77051205/5a3aac05-6fff-4ad6-8762-abfa597b9f14">

**Comment by gabe565** [comment]
@slingr-dev Thanks for raising this issue! I'm pushing a fix for this, and will add native token support soon

**Comment by gabe565** [comment]
@slingr-dev I have added official support for API tokens!
