### ISSUE TITLE
failure in mmol <-> mg/dl conversion renders no data

### ISSUE THREAD

**Issue by slingr-dev** [gabe565/nightscout-menu-bar#90]
I had originally fixed this way back on a forked version, but I never issued a pull request and I don't have any of the old source files anymore, but IIRC its something to do with nightscout wanting to deal in mg/gl whole numbers and mmol having non-integers when dealing with both the glucose value (6.3) and the trending direction (i.e. -0.3↘).

Happy to throw a token your way to test against my NS instance.

<img width="676" alt="Screenshot 2024-10-11 at 10 57 36" src="https://github.com/user-attachments/assets/03fbe33d-0135-4a2e-8048-74ce4ad289ca">
<img width="679" alt="Screenshot 2024-10-11 at 11 01 39" src="https://github.com/user-attachments/assets/c3acfdbe-6619-4b3f-a75f-d8809a4aa469">

**Comment by gabe565** [comment]
@slingr-dev Sorry for the late reply, somehow I missed the notification for this issue! Hmm I didn't realize Nightscout changed the types to floats in specific cases. I'll work on a fix now!

**Comment by gabe565** [comment]
@slingr-dev Either a token or an example JSON response from `/api/v2/properties` would probably be helpful. I thought Nightscout's API only returned mg/dl, even if it was set to use mmol. To keep it private, can you send one of these through my [contact form](https://gabecook.com/connect)?

**Comment by gabe565** [comment]
@slingr-dev Actually, I think I see the issue. The delta values contain an entry for the scaled value (which is converted to mmol by Nightscout) and another value which is always mgdl. My original intention was to use the mgdl value, and convert it based on the chosen unit.

I'm currently testing a fix!

**Comment by gabe565** [comment]
@slingr-dev Ok, I just released [v0.4.1](https://github.com/gabe565/nightscout-menu-bar/releases/tag/v0.4.1) which should solve your issue. When you get a chance, can you update and test?

**Comment by slingr-dev** [comment]
Hey Gabe, I've been overseas for a month and, in true fashion, one of my 3 Dexcom sensors failed so I've been without a CGM for the last week. I'll be able to test this tomorrow when I get back to North America. I appreciate the great work! Please let the community know if you have a BuyMeACoffee or similar-type link where we can show support for your efforts :)

**Comment by slingr-dev** [comment]
@gabe565 confirmed fixed
